---
apiVersion: v1
kind: Service
metadata:
  name: payment-db
  labels:
    name: payment-db
  namespace: microshop
spec:
  ports:
    # the port that this service should serve on
  - port: 27017
    targetPort: 27017
  selector:
    name: payment-db

